pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage("Sonarqube Analysis"){
            steps{
                echo "====++++executing Sonarqube Analysis++++===="
                withSonarQubeEnv('SonarQube') {
                sh 'mvn sonar:sonar'
            }
            }
            post{
                always{
                    echo "====++++always++++===="
                }
                success{
                    echo "====++++Sonarqube Analysis executed successfully++++===="
                }
                failure{
                    echo "====++++Sonarqube Analysis execution failed++++===="
                }
        
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
